javascript:
  - changed-files:
      - any-glob-to-any-file:
          - src/**/*
          - scripts/**/*
          - public/**/*
          - .tool-versions
          - docs/**/*
          - AGENTS.md

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - AGENTS.md
          - README.md

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
          - next.config.ts
          - next-env.d.ts
          - postcss.config.json
          - biome.json
          - jest.config.js
          - tsconfig.json
          - stylelint.config.mjs
          - knip.json

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - .tool-versions
          - package.json
          - pnpm-lock.yaml
          - pnpm-workspace.yaml
          - patches/**/*

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
